[package]
name = "rfm22b-rs"
version = "0.1.0"
authors = ["Radosław Dejnek <radek.dejnek@gmail.com>"]
edition = "2018"

[dependencies.embedded-hal]
version = "0.2.3"

[dependencies.nb]
version = "0.1.2"